name: Deploy

on:
  repository_dispatch:
    types: [release]
  release:
    types: [published]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Build App
        run: npm run build --if-present
      - name: NPM Deploy
        run: npm publish
